### ISSUE TITLE
webpacker 3.2.1 hardcodes uglifyOptions: { ecma: 8 } which ignores Babel target options and breaks IE11 compatibility

### ISSUE THREAD

**Issue by shepmaster** [rails/webpacker#1235]
Dumping out the Webpack config in production mode, I have this piece of configuration:

```js
"uglifyOptions": {
  "output": {
    "ascii_only": true
  },
  "ie8": false,
  "ecma": 8,
  "warnings": false,
  "mangle": {
    "safari10": true
  },
  "compress": {
    "warnings": false,
    "comparisons": false
  }
}
```

This seems to be from  a5e76b80887c929105221a4333ed0c05ac99d17e and thus introduced in 3.2.1.

This affects us because we are using the `remarkable` package, which contains some JS like `{Afr:"𝔄",}`, which Babel properly converts to `{Afr:"\uD835\uDD04",}`, but then Uglify shortens back to `{Afr:"\u{1d504}",}`. This latter syntax isn't supported by IE11, causing issues in production, specifically the error "Expected hexadecimal digit".

Related to  #1211

**Comment by shepmaster** [comment]
You can see the uglify behavior on this [online example](https://skalman.github.io/UglifyJS-online/). Set the input to `a = "\uD835\uDD04";` and set the appropriate options:

```js
output: {
    ascii_only       : true,
    ecma             : 5,
```

![image](https://user-images.githubusercontent.com/174509/35584367-cb19b6b2-05c2-11e8-8925-1e21b0f59182.png)

```js
output: {
    ascii_only       : true,
    ecma             : 8,
```

![image](https://user-images.githubusercontent.com/174509/35584377-d546d3ea-05c2-11e8-94a0-9d31a7ab9c97.png)

**Comment by danielma** [comment]
We are experiencing the same issue, and just fixed it by changing our `production.js` to 

```js
const environment = require('./environment')

environment.plugins.get("UglifyJs").options.uglifyOptions.ecma = 5

module.exports = environment.toWebpackConfig()
```

**Comment by gauravtiwari** [comment]
Will push an option for this in environment during the weekend. In meantime, please use the solution suggested by @danielma

**Comment by tbsvttr** [comment]
Even with Webpacker 3.2.2 both in package.json as well as Gemfile it only works with the fix by @danielma for me.

@danielma You are **the** man!

**Comment by clarketus** [comment]
I just spent a looong time googling for a solution to this. I'm going to add what I was searching for as a comment here to hopefully save other people time.

The IE11 error I was getting was: 
SCRIPT1003: Expected ':'
This was occurring in webpack/bootstrap.js

The suggested solution here worked for me!

**Comment by tbsvttr** [comment]
@clarketus Very good idea!

@gauravtiwari When will this be fixed?

**Comment by gauravtiwari** [comment]
I am aiming to provide an option for this in Webpacker 4.0 but for now the solution suggested above is simple enough to use if you need to support ES5. Thank you.

**Comment by bjankord** [comment]
+1 to a config option. I think there are still a decent number of teams that need ES5 to support IE11. Having a first class option to change this config will be helpful.

**Comment by triskweline** [comment]
The [solution](https://github.com/rails/webpacker/issues/1235#issuecomment-362417050) by @danielma works for us, thank you.

This took a really long time to find out :cry:  We thought there was a mistake with our Babel configuration.

Since Webpacker aims to provide a preconfigured pipeline that includes both Babel and UglifyJS by default, maybe the default config could target the same browsers in all processing steps? Webpacker's [default `.babelrc`](https://github.com/rails/webpacker/blob/15e100bb55c895c8801a88d06561ec6c7f2b93d6/lib/install/config/.babelrc) targets IE11, but with `{ ecma: 8 }` UglifyJS will re-break the code that Babel just dumbed down to be compatible with IE11.

**Comment by lakim** [comment]
Just bumped into this problem.
We've investigated for a very long time before finding this issue. Wish we'd seen it before.

The following code in our vendor pack was using ES2015 syntax:
```javascript
var r=e[i]={i,l:!1,exports:{}}
```
and was throwing this error in IE11:
```
SCRIPT1003: Expected ':'
File: vendor-43254822d2b4661a48f6.js, Line: 1, Column: 438878
```

After @danielma 's fix, the code looked like proper ES5:
```
var r=e[i]={i:i,l:!1,exports:{}}
```

I agree with @triskweline 
I suspect that the majority of babel users are using it to transpile to ES5. Seeing UglifyJs ruining it is clearly not what they are expecting and they will have a hard time to understand where the issue is coming from.
The default config should be `{ ecma: 5 }` and be configurable for those who will only target browsers that support ES2015, not the other way around.

**Comment by renchap** [comment]
If you updated to Webpacker 4 (Webpack 4) and are using the default config, the workaround is to add  this line to your `production.js`:
```es6
environment.config.optimization.minimizer[0].options.uglifyOptions.ecma = undefined // the default, or 5 if you want it explicitely
```

**Comment by summera** [comment]
This is quite a big issue IMHO and took hours to track down. @gauravtiwari possible to get a fix in for this soon?

**Comment by 1st8** [comment]
Thank you, so glad I found this issue.

Just to make this a bit more googleable, my problem was with DraftJS and IE11 telling me

```
SCRIPT1023: Expected hexadecimal digit
```

with this statement

```
n.textContent="\u{1f4f7}"
```

**Comment by bidva** [comment]
I have same problem. setting ecma 5 didn't fix the issue 
still I get Syntax error on this 

`r=e=>`

**Comment by renatodeleao** [comment]
4 hours later and only after a desperate  `"SCRIPT1003: Expected ':'` search I got here! Just want to leave a big f*ing thanks to @danielma.

**Comment by gauravtiwari** [comment]
@renatodeleao This is fixed on the master branch will make a release later in the week.

**Comment by marvwhere** [comment]
using `"4917047aae99aca1738dd06df4e60713549eef44"` latest master in my Gemfile, and still running into this error.  even if i only have 

`import 'jquery'`

in my application.js

any ideas? )= 

rails 5.2

my webpacker.yml is pretty defaulty

```staging:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true```

**Comment by decafdennis** [comment]
It does look like https://github.com/rails/webpacker/issues/1235#issuecomment-362417050 (which i didn't see) is essentially the same. Well, glad it worked. :)

**Comment by kmoo** [comment]
@gauravtiwari, is this fix going to be released? I noticed there has not been a release since this fix was merged

**Comment by r-obert** [comment]
@kmoo `v3.5.5` does not fix this issue. the patch from @danielma is still needed.
the current status is that rails5+ is shipping with a stack that has broken IE11 support.

**Comment by gauravtiwari** [comment]
@r-obert Have you updated both gem and npm package to 3.5.5? https://github.com/rails/webpacker/blob/3-x-stable/package/environments/production.js#L16

**Comment by r-obert** [comment]
@gauravtiwari i updated the Gemfile, but not package.json.
do i also need to update `rails/webpacker`?

**Comment by gauravtiwari** [comment]
Yep, `yarn add @rails/webpacker` or `yarn upgrade @rails/webpacker`

**Comment by r-obert** [comment]
thanks! will try and post back.

**Comment by r-obert** [comment]
it works! i updated the Gemfile and npm package, then all good. thank you @gauravtiwari

**Comment by gauravtiwari** [comment]
Great, thanks for reporting back 👍 

Closing this issue...

**Comment by paulupendo** [comment]
> Thank you, so glad I found this issue.
> 
> Just to make this a bit more googleable, my problem was with DraftJS and IE11 telling me
> 
> ```
> SCRIPT1023: Expected hexadecimal digit
> ```
> with this statement
> 
> ```
> n.textContent="\u{1f4f7}"
> ```

@1st8 How did you fix this? I'm having the same issue.

**Comment by 1st8** [comment]
@paulupendo probably with the solution above: https://github.com/rails/webpacker/issues/1235#issuecomment-362417050

I can check for sure on monday if it doesn't work.

**Comment by JamesPlayer** [comment]
Just upgraded from webpacker v3 to v4. I had been using @danielma's solution :
```
environment.plugins.get("UglifyJs").options.uglifyOptions.ecma = 5;
```
But that now throws an error in v4 `Error: Item UglifyJs not found`, so I tried @renchap's v4 solution: 
```
environment.config.optimization.minimizer[0].options.uglifyOptions.ecma = 5;
```
but that gives me an error: `TypeError: Cannot set property 'ecma' of undefined`

Any ideas how to fix for webpacker v4?

**Comment by martinsp** [comment]
I think it should work out of the box for v4. It now uses TerserPlugin, and the corresponding configuration settings are here: https://github.com/rails/webpacker/blob/1e9e2d04de100a3d5beb085ccaad061440265dc7/package/environments/production.js#L48-L52

**Comment by shepmaster** [comment]
> I think it should work out of the box for v4. It now uses TerserPlugin

This was the result of our investigation as well. However, the workaround [should not have been needed since 3.5.5](https://github.com/rails/webpacker/issues/1235#issuecomment-401427084) anyway.
