### ISSUE TITLE
CSS z-indexes are getting compressed

### ISSUE THREAD

**Issue by tyvdh** [rails/webpacker#1663]
Locally I can set a z-index of 10 but when I run through production it get's compressed to 3. Apparently this is a cssnano thing but it doesn't appear you are utilizing cssnano. Any idea where this could be coming from and how I could disable this behavior?

**Comment by tyvdh** [comment]
Worth noting if I roll back to 3.5.3 it's no longer an issue.

**Comment by Meekohi** [comment]
I am seeing the same issue, presume it is related to: https://github.com/vuejs-templates/webpack/issues/614

**Comment by Meekohi** [comment]
I'd guess there is some way to pass `safe: true` down into the CSS processing from `vue-loader` but I can't tell how to do that exactly.

**Comment by Meekohi** [comment]
Based on other PRs that have been accepted, I suspect that upgrading to `vue-loader` v15 will fix this problem, but the migration path is pretty complicated. I spent some time on it, but getting cryptic errors:
```
Compiling…
Compilation failed:
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[7] should be an object.
   -> A rule
```
and not sure how to proceed. Not sure I understand the purpose of webpacker obfuscating the actual webpack config file behind `environment.js`, makes it very hard to modify or debug.

**Comment by Meekohi** [comment]
see also: `vue-loader` migration guide at https://vue-loader.vuejs.org/migrating.html

**Comment by tyvdh** [comment]
I’m going to echo this as my biggest gripe with webpacker. It’s very difficult to tweak as everything seems to be overwrites rather than actually setting or adjusting from the ground up. There may be legitimate reasons for this design choice but it makes this package a pain to use even if it is still the best way to get webpack into a Rails app

**Comment by jnimety** [comment]
Adding the following in my production.js webpack config fixed the issue for me. Perhaps this should be a webpacker default. FWIW we do not use Vue.

`environment.plugins.get('OptimizeCSSAssets').options.cssProcessorOptions.safe = true`

 It took me a while to figure out which (new) plugin was causing this issue, what webpacker named it, and that it is only included in the production environment. It would be great if plugin configurations were loaded via a separate config file in `config/webpack` so they could be easily adjusted in one place. The files could serve as documentation of default values and allow changes, much like the rails environment config files.

**Comment by gauravtiwari** [comment]
Is this a problem in latest RC?

**Comment by kylefox** [comment]
@ahyanarizky You could try setting `NODE_ENV=production`, assuming you're adding this config to `config/webpack/production.js`.

We're using Webpacker 3.5.5, so your mileage may vary if you're running a 4.0 RC.

**Comment by gauravtiwari** [comment]
@kylefox We have fixed this in latest RC, it uses postcss safe parser so you don't need to specify the option.

**Comment by Meekohi** [comment]
Upgrade from 3.5.5 to 3.6.0 and finding this is still an issue?

**Comment by Meekohi** [comment]
(Also @kylefox's fix did work for us, thanks!)

**Comment by guillaumebriday** [comment]
If it's good for you feel free to close the issue please 👍
