### ISSUE TITLE
Webpacker 6.x - Compile in production mode generates errors

### ISSUE THREAD

**Issue by pedrofurtado** [rails/webpacker#2828]
@gauravtiwari The webpacker 6.x is almost 100% done here! 🎉 

Occurs some strange situation here. The `rails webpacker:compile` in development mode works very well, generate the packs and so on. But when I execute `NODE_ENV=production RAILS_ENV=production rails webpacker:compile` (without changing any files, just putting the env vars in command), generates these errors in terminal:

```bash
# rails webpacker:compile
webpack 5.11.0 compiled successfully in 18424 ms

# NODE_ENV=production RAILS_ENV=production rails webpacker:compile
ERROR in Conflict: Multiple assets emit different content to the same filename XXXXX
webpack 5.11.0 compiled with YYYY errors in 117517 ms
```

Maybe this can be related with some configuration that only occurs in production-only or development-only?

**Comment by pedrofurtado** [comment]
@gauravtiwari  Well, I am confused now hehehe 👀 

I emptied the file `app/javascript/packs/application.js`, and I executed `RAILS_ENV=production NODE_ENV=production rails webpacker:compile` and the output of terminal was this below:

```bash
rm -Rf public/packs/ && RAILS_ENV=production NODE_ENV=production rails webpacker:compile
Warning: you are using an unstable release of Node.js (v15.4.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
Compiling...
Compilation failed:
[webpack-cli] Compilation finished
assets by status 1.46 KiB [cached] 3 assets
Entrypoint application = js/runtime-9cb7c7d261373f0e7c24.js js/application-a362ed875d9694b58391.js 1 auxiliary asset
runtime modules 2.65 KiB 2 modules
./app/javascript/packs/application.js 1 bytes [built] [code generated]

ERROR in Conflict: Multiple assets emit different content to the same filename js/.br

webpack 5.11.0 compiled with 1 error in 1133 ms
[root@localhost vagrant]#
```

**Comment by gauravtiwari** [comment]
Thanks @pedrofurtado I will take a look today and get this fixed.

**Comment by pedrofurtado** [comment]
Fixed! Thanks @gauravtiwari 🤝

**Comment by afshing** [comment]
I have the exact same issue, and beta 2 did not resolve the problem.
Webpack: 5.11.1
Webpacker: 6.0.0-beta.2
Webpack-cli: 4.3.1

I have three entry points. I emptied all three, and similar to @pedrofurtado, it all works in the dev environment, but in the production environment, I get this error

```
ERROR in Conflict: Multiple assets emit different content to the same filename js/.br

ERROR in Conflict: Multiple assets emit different content to the same filename js/.br

ERROR in Conflict: Multiple assets emit different content to the same filename js/.br

ERROR in Conflict: Multiple assets emit different content to the same filename js/.br

ERROR in Conflict: Multiple assets emit different content to the same filename js/.br

webpack 5.12.1 compiled with 5 errors in 1099 ms
```


I am not sure if I should open a new issue or provide more information.

**Comment by pedrofurtado** [comment]
@afshing Check if you upgrade the webpacker gem and the JS package `@rails/webpacker` to beta.2 🤝

**Comment by afshing** [comment]
> @afshing Check if you upgrade the webpacker gem and the JS package `@rails/webpacker` to beta2 (both) 🤝

The gem was on `pre-2`, but even when I tried to force it to be on `beta-2`, I got the same result.

The project is relatively big, so I can not provide more details, but I will keep this thread posted if I found anything

**Comment by timmyd87** [comment]
I have the same error in production and can confirm im running beta2 in both gem and package.json. I can replicate the error if i run rails assets:precompile locally however
