### ISSUE TITLE
Pack tags are empty during tests

### ISSUE THREAD

**Issue by rhymes** [rails/webpacker#659]
I'm trying to have a Capybara / JS test work with webpacker but it keeps failing for the following reason:

```
DevicesPageJavaScriptTest#test_should_display_information:
Capybara::Poltergeist::JavascriptError: One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
    at http://127.0.0.1:57467/assets/application-64ba59bbca44489859b5ec062c1712adb6e7d109cf7a899892cb8a93ffd49932.js:2227 in global code
```

As you can see it can't find jQuery, which is bundled by webpack. At the current moment the test app is using webpack for third party dependencies and is still using the asset pipeline for all the custom JS.

I put a breakpoint right before the "visit" action that triggers that error, I opened in Chrome the HTML page and in the source code I couldn't find any references to the "packs" application.js and application.css. Meaning that the following lines in the layout erb file result in nothing in testing mode:

```html
<%= stylesheet_pack_tag 'application', media: 'all' %>
<%= javascript_pack_tag "application" %>
```

though they work perfectly fine in development mode.

I've checked the manifest.json as well and here is the content:

**development** inside public/packs/manifest.json

```json
{
  "application.css": "http://0.0.0.0:8080/packs/application.css",
  "application.js": "http://0.0.0.0:8080/packs/application.js",
  "fontawesome-webfont.eot": "http://0.0.0.0:8080/packs/fontawesome-webfont.eot",
  "fontawesome-webfont.svg": "http://0.0.0.0:8080/packs/fontawesome-webfont.svg",
  "fontawesome-webfont.ttf": "http://0.0.0.0:8080/packs/fontawesome-webfont.ttf",
  "fontawesome-webfont.woff": "http://0.0.0.0:8080/packs/fontawesome-webfont.woff",
  "fontawesome-webfont.woff2": "http://0.0.0.0:8080/packs/fontawesome-webfont.woff2",
  "glyphicons-halflings-regular.eot": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.eot",
  "glyphicons-halflings-regular.svg": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.svg",
  "glyphicons-halflings-regular.ttf": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.ttf",
  "glyphicons-halflings-regular.woff": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.woff",
  "glyphicons-halflings-regular.woff2": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.woff2"
}
```

**test** inside public/packs-test/manifest.json

```json
{
  "application.css": "/packs-test/application.css",
  "application.js": "/packs-test/application.js",
  "fontawesome-webfont.eot": "/packs-test/fontawesome-webfont.eot",
  "fontawesome-webfont.svg": "/packs-test/fontawesome-webfont.svg",
  "fontawesome-webfont.ttf": "/packs-test/fontawesome-webfont.ttf",
  "fontawesome-webfont.woff": "/packs-test/fontawesome-webfont.woff",
  "fontawesome-webfont.woff2": "/packs-test/fontawesome-webfont.woff2",
  "glyphicons-halflings-regular.eot": "/packs-test/glyphicons-halflings-regular.eot",
  "glyphicons-halflings-regular.svg": "/packs-test/glyphicons-halflings-regular.svg",
  "glyphicons-halflings-regular.ttf": "/packs-test/glyphicons-halflings-regular.ttf",
  "glyphicons-halflings-regular.woff": "/packs-test/glyphicons-halflings-regular.woff",
  "glyphicons-halflings-regular.woff2": "/packs-test/glyphicons-halflings-regular.woff2"
}
```

```sh
➜  ls public/packs-test
application.css                    fontawesome-webfont.ttf            glyphicons-halflings-regular.svg   manifest.json
application.js                     fontawesome-webfont.woff           glyphicons-halflings-regular.ttf
fontawesome-webfont.eot            fontawesome-webfont.woff2          glyphicons-halflings-regular.woff
fontawesome-webfont.svg            glyphicons-halflings-regular.eot   glyphicons-halflings-regular.woff2
```

The files are there but Capybara + Poltergeist can't find the pack. Am I missing something?

Thank you

**Comment by gauravtiwari** [comment]
@rhymes Please try latest master 👍  We fixed some related issues

**Comment by gauravtiwari** [comment]
You would need to run `webpacker:install` tasks though

**Comment by rhymes** [comment]
Thanks @gauravtiwari - I've updated webpacker and installed again but it still doesn't work. Is there any configuration step I'm missing?

Thanks!

**Comment by gauravtiwari** [comment]
@rhymes That's strange. What Rails version are you using? Are you sure the layout where these helper tags are included is the page you are visiting in tests? Usually it would just fail if there is no pack but you getting some `$` error right? That means packs are getting loaded at some point

**Comment by rhymes** [comment]
@gauravtiwari Rails 5.1.3

It works now. There was a typo in the pack name and it wasn't picking it up.

I'll keep tracking HEAD for now :-)

Thanks again for the great work. I'm off learning ES6 ;-)

**Comment by gauravtiwari** [comment]
Awesome 👍
